---
title: "Exploration of Air Quality Index Geographic and Seasonal Factors"
subtitle: "Proposal"
author: 
  - name: "Team Name - Jack Stevens, Lila Carruthers, Rithik Mehta"
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: "Project description"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import numpy as np
```

## Dataset

```{python}
#| label: load-dataset
#| message: false
```

A brief description of your dataset including its provenance, dimensions, etc. as well as the reason why you chose this dataset.

Make sure to load the data and use inline code for some of this information.

## Questions

1. How the Air Quality Index (AQI) changes across different regions and over time: Are there any extreme fluctuations in AQI within certain regions or shifts in patterns throughout the year?

2. How do AQI factors change over time: Are there seasonality or geographic factors that contribute to the AQI or its key contributors?

## Analysis plan
**Week 1 - EDA / Preprocessing**

This week should be focused on understanding the data and any interesting relationships between the features and the target variable (AQI value).
Next, using the findings from the EDA stage, the focus should be handling any data quality issues (missing value, encoding categorical variables, scaling values) and removing any unnecessary columns.
By the end of this week, we should have a summary of key findings from the EDA and a preprocessed dataset.
 
**Week 2 - Modeling**

This week should be focused on performing advanced modeling techniques, such as OLS and other regression models to understand the importance of the features and rank the influence that the features have on the target variable. By the end of this week, we should have a list of features that contribute to the Air Quality Index.
 
**Week 3 - Dashboard Wireframing**

This week should be focused on designing and mapping out the metrics to use on the interactive dashboard. This should include the type of visuals, the expected interactions of variables and require data structures to build the report. By the end of this week, we should have a rough sketch of the dashboard that answers the questions above.
 
**Week 4 - Dashboard Building**

This week should be focused on implementing wireframed dashboards using the Stream-lit library. This should include the building, testing, and finding key interactions between the visuals to demonstrate during the final presentation. By the end of this week, we should have a deployed dashboard with 2-3 patterns identified by the dashboard.
 
**Week 5 - Final Report**

This week should be focused on completing the final write-up and presentation. The group members for each week should discuss their decision about the work they were responsible for. By the end of the week, we should have a finalized report and recorded video. 


## Repository Structure 

**Data-** 

This folder should contain the datasets that are being used for this analysis. This folder should have a README.md  that contains the description of the dataset as well. 

**Image-** 

This folder should contain any graphs / images that we plan on using for the presentation. 

**_extra-**

This folder should contain any additional notebooks that we would like to store for generating graphs. 

**Other Files/Folders -**

Any other files/folders are responsible for the generation and content presented in the quarto site. 
